% Ejercicio 5 a) - P6

addpath('Funciones');

% Limpiar
clear all; close all; clc;

% Índice de tiempo
Ts = 1/1000;
dt = Ts/1000;
L = 30*1e-3;
t = -round(L/Ts)*Ts:dt:round(L/Ts)*Ts;

% Índice de tiempo discreto
n = -round(L/Ts):round(L/Ts);

% Señal x(t)=3sen(100πt)
x = 3*sin(100*pi*t);

% Señal muestreada x[n] = x(n.Ts)
xn = x(  round((n+round(30*1e-3/Ts))*Ts/dt) + 1);

plotCompleto(t,x,...
    'Hold',1,...
    'AxisLimits',[ -31*1e-3 31*1e-3 -4 4],...
    'XLabel','t',...
    'Title','Señal x(t) = 3sen(100πt) y su muestreo x[n] = x(n.T_s)',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);


stemCompleto(n*Ts,xn,...
  'Hold',1,...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','b',...
  'MarkerFaceColor','b',...
  'MarkerEdgeColor','b',...
  'LineWidth',3);

