% Ejercicio 2 a) V - P6

addpath('Funciones');

% Limpiar
clear all; close all; clc;

% Índice de tiempo
Ts = 0.5;
dt = Ts/1000;
L = 10;
t = -round(L/Ts)*Ts:dt:round(L/Ts)*Ts;

% Índice de tiempo discreto
n = -round(L/Ts):round(L/Ts);

% Señal x(t)=sinc(t)
x = sinc(t);

% Señal muestreada x[n] = x(n.Ts)
xn = x(  round((n+round(L/Ts))*Ts/dt) + 1);



% Índice de frecuencia
ds = 1e-4;
S = 2;
s = -S:ds:S;

% TFTD de x[n]
Xn = (1/Ts)*cajon(s/Ts);

% TFTD de x[n] (aproximación)
Xn_aprox = zeros(size(s));
for i = 1:length(s)
  Xn_aprox(i) = sum(xn.*exp(1i*2*pi*s(i)*n));
end

plotCompleto(t,x,...
    'Hold',1,...
    'AxisLimits',[ -L L -4 4],...
    'Subplot',[3 1 1],...
    'XLabel','t',...
    'Title','Señal x(t) = 3sen(100πt) y su muestreo x[n] = x(n.T_s)',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);


stemCompleto(n*Ts,xn,...
  'Hold',1,...
  'Subplot',[3 1 1],...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','b',...
  'MarkerFaceColor','b',...
  'MarkerEdgeColor','b',...
  'LineWidth',3);

legend('x(t)','x[n]=x(n.Ts)','location','northwest');


plotCompleto(s,Xn_aprox,...
    'Hold',1,...
    'AxisLimits',[ -S S -4 4],...
    'Subplot',[3 1 2],...
    'XLabel','s',...
    'Title','Señal TFTD {x[n]} (s) aproximación',...
    'FontSize',20,...
    'LineStyle','b.-',...
    'LineWidth',3);


plotCompleto(s,Xn,...
    'Hold',1,...
    'AxisLimits',[ -S S -4 4],...
    'Subplot',[3 1 3],...
    'XLabel','s',...
    'Title','Señal TFTD {x[n]} (s)',...
    'FontSize',20,...
    'LineStyle','b.-',...
    'LineWidth',3);


