% Ej3 a) - P5

addpath('Funciones');

% Limpiar todo
clear all; close all; clc;

% Vector de tiempo
S = 1/2;
ds = 1e-4;
s = -S:ds:S;

% Gráfica de la TFTD de la rta impulsional del sistema

% Se halló de antemano H(e^(j2pi.s))
H = (1./(1-(1/2).*exp(1j.*2.*pi.*s))) + ((exp(1j.*2.*pi.*s))./(1-(1/2).*exp(1j.*2.*pi.*s)));

plotCompleto(s,abs(H),...
    'Hold',1,...
    'Subplot',[2 1 1],...
    'AxisLimits',[-S S -5 5],...
    'XLabel','t',...
    'Title','Ej 5 a) - P5 - Módulo de la TFTD de la rta impulsional',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

legend('|H(e\^(j.2pi.s)| , |s| <= 1/2','location','northwest');

plotCompleto(s,angle(H),...
    'Hold',1,...
    'Subplot',[2 1 2],...
    'AxisLimits',[-S S -5 5],...
    'XLabel','t',...
    'Title','Ej 5 a) - P5 - Fase de la TFTD de la rta impulsional',...
    'FontSize',20,...
    'LineStyle','b.-',...
    'LineWidth',3);

legend('angle(H(exp\^(j.2pi.s)) , |s| <= 1/2','location','northwest');

