%% Ejercicio 5 c) - P5

addpath('Funciones');

% Limpiar
clear all; close all; clc;

% Índice de tiempo
K = 100;
n = -K:K;

% Índice de frecuencia
ds = 1e-3;
s = -2:ds:2;

% Señal dada
S0 = 0.1;
x = 2*cos(2*pi*S0*n);

% TFTD Analítica
% NO TENGO IDEA COMO HACERLA
%X = deltaKronecker(s-S0) + deltaKronecker(s+S0);

% TFTD Aproximación

X_aprox = zeros(size(s));
for i = 1:length(s)
  X_aprox(i) = sum(x.*exp(1i*2*pi*s(i)*n));
end



%% -- Gráficas --


stemCompleto(n,x,...
  'Hold',1,...
  'Subplot',[3 1 1],...
  'AxisLimits',[-(K+2) (K+2) -3 3],...
  'XLabel','n',...
  'Title','Señal x[n] = 2cos(2.pi.s0.n)',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

legend('x[n]','location','northwest');

%{
plotCompleto(s,X,...
    'Hold',1,...
    'AxisLimits',[ -0.5 0.5 -2 3],...
    'Subplot',[3 1 2],...
    'XLabel','s',...
    'Title','TFTD de la señal x[n] = 2cos(2.pi.s0.n)',...
    'FontSize',20,...
    'LineStyle','b.-',...
    'LineWidth',3);

legend('X(s)','location','northwest');
%}


plotCompleto(s,real(X_aprox),...
    'Hold',1,...
    'AxisLimits',[ -0.5 0.5 -10 max(X_aprox)*1.1],...
    'Subplot',[3 1 3],...
    'XLabel','s',...
    'Title','Aproximación de la TFTD de la señal x[n] = a^n.u[n]',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

stemCompleto(S0,max(X_aprox)*2,...
  'Hold',1,...
  'Subplot',[3 1 3],...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','b',...
  'MarkerFaceColor','b',...
  'MarkerEdgeColor','b',...
  'LineWidth',3);
stemCompleto(-S0,max(X_aprox)*2,...
  'Hold',1,...
  'Subplot',[3 1 3],...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','b',...
  'MarkerFaceColor','b',...
  'MarkerEdgeColor','b',...
  'LineWidth',3);


legend('imag(X_a_p_r_o_x(s))','real(X_a_p_r_o_x(s))','location','northwest');


