%% Ejericio 5 b) - P5

addpath('Funciones');

% Limpiar
clear all; close all; clc;

% Índice de tiempo n
K = 3;
n = -K:K;

% Índice de frecuencia s
ds = 1e-4;
s = -0.5:ds:0.5;

% Señal dada
a = 0.5;
x = (a.^n).*escalon(n);

% TFTD analítica de la señal
X = 1./(1-a*exp(-1i*2*pi*s));

% Aproximación de la TFTD de x[n]

X_aprox = zeros(size(s));
for k = 1:length(s)
  X_aprox(k) = sum(x.*exp(-1i*2*pi*s(k)*n));
end;


%% -- Gráficas --


stemCompleto(n,x,...
  'Hold',1,...
  'Subplot',[3 1 1],...
  'AxisLimits',[-(K+2) (K+2) -1 1],...
  'XLabel','n',...
  'Title','Señal x[n] = a^n.u[n]',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

legend('x[n]','location','northwest');


plotCompleto(s,abs(X_aprox),...
    'Hold',1,...
    'AxisLimits',[ -0.5 0.5 -5 5],...
    'Subplot',[3 1 2],...
    'XLabel','s',...
    'Title','Aproximación de la TFTD de la señal x[n] = a^n.u[n]',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

legend('X_a_p_r_o_x(s)','location','northwest');


plotCompleto(s,abs(X),...
    'Hold',1,...
    'AxisLimits',[ -0.5 0.5 -5 5],...
    'Subplot',[3 1 3],...
    'XLabel','s',...
    'Title','TFTD de la señal x[n] = a^n.u[n]',...
    'FontSize',20,...
    'LineStyle','b.-',...
    'LineWidth',3);

legend('X(s)','location','northwest');

