% Limpiar todo

clear all; close all; clc

% Calculo de la TFTD de x[n] = ⊓ N [n]

K = 10;
n = -K:K;
N = 4
x = cajon(n/(2*N+1));
S = 2
ds = 0.001;
s = -S:ds:S
X_aprox = zeros(size(s));
for k = 1:length(s)
  X_aprox(k) = sum(x.*exp(-1i*2*pi*s(k)*n));
end

X = sin((2*N+1)*pi*s)./sin(pi*s);
X(mod(s,1) == 0) = 2*N+1;

stemCompleto(n,x,...
  'Hold',1,...
  'Subplot',[3 1 1],...
  'XLabel','n',...
  'Title','Señal x[n] = ⊓ N [n]',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

legend('x[n]','location','northwest');

plotCompleto(s,X_aprox,...
    'Hold',1,...
    'Subplot',[3 1 2],...
    'XLabel','s',...
    'Title','Aproximación de la TFTD de la señal x[n] = ⊓ N [n]',...
    'FontSize',20,...
    'LineStyle','b.-',...
    'LineWidth',3);

legend('X_a_p_r_o_x(s)','location','northwest');

plotCompleto(s,X,...
    'Hold',1,...
    'Subplot',[3 1 3],...
    'XLabel','s',...
    'Title','TFTD de la señal x[n] = ⊓ N [n]',...
    'FontSize',20,...
    'LineStyle','b.-',...
    'LineWidth',3);

legend('X(s)','location','northwest');


