addpath('Funciones');

% Vector de tiempo a utilizar
dt = 0.02;
t = -2:dt:2;
% Vector de frecuencia a utilizar
df = 0.01;
f = -20:df:20;

% Se tiene la señal x(t):
x = tri(t/2);

% Inciso a) TF analítica de x(t)
Xa = 2*sinc(2*f).^2;

plotCompleto(f,Xa,...
    'Hold',1,...
    'Subplot',[2 1 1],...
    'AxisLimits',[-4 4 -1 3],...
    'XLabel','f',...
    'Title','Ej 6 a) - P4',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

legend('Xa(f)','location','northwest');


% Inciso b) Aproximación de la TF de x(t)
Xb = zeros(size(f));
for k = 1:length(f)
  Xb(k) = sum(dt*x.*exp(-1i*2*pi*f(k)*t));
end

plotCompleto(f,Xb,...
    'Hold',1,...
    'Subplot',[2 1 2],...
    'AxisLimits',[-4 4 -1 3],...
    'XLabel','f',...
    'Title','Ej 6 b) - P4',...
    'FontSize',20,...
    'LineStyle','b.-',...
    'LineWidth',3);

legend('Xb(f)','location','northwest');
