addpath('Funciones');

% Al graficar se nota que el cajon h(t) (rta impulsional del
% sistema) del ejercicio tiene un ancho igual al período de
% x(t), por lo tanto, el la integral del producto de estas 2
% funciones, sin importar el desfase entre ambas, dará siempre
% 0, es por esto que su convolución y por lo tanto la salida
% del sistema es nula.

% Vector de tiempo
dt = 1e-3;
t=-10:dt:10

% Entrada al sistema
x = cos(5*pi.*t);

% Rta impulsional del sistema
h = cajon((5/2).*(t-1/5));

% Producto de la entrada y de la rta impulsional
z = x.*y;

plotCompleto(t,x,...
    'Hold',1,...
    'AxisLimits',[-2 2 -3 3],...
    'XLabel','t',...
    'Title','Ej 5 b) - P6',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

plotCompleto(t,c,...
    'Hold',1,...
    'AxisLimits',[-2 2 -3 3],...
    'FontSize',20,...
    'LineStyle','b.-',...
    'LineWidth',3);

plotCompleto(t,z,...
    'Hold',1,...
    'AxisLimits',[-2 2 -3 3],...
    'XLabel','t',...
    'Title','Ej 5 b) - P6',...
    'FontSize',20,...
    'LineStyle','y.-',...
    'LineWidth',3);

legend('x(t) = cos(5pit)','y(t) = {x*h}(t)','z(t) = x(t).y(t)','location','northwest');

