addpath('Funciones');

% Buscar funciones mean() y movavg()

% Limpiar todo
clear all; close all; clc;

% Constantes del sistema
A = 1; % Real
K = 4; % Entero
N = 1; % Ancho de ventana es 2N + 1

% Ancho de n que voy a ver
n = -20:20;

% Señal de entrada del sistema
x = A + sin(2.*pi.*(n)./K);

% Señal de salida del sistema
y = Sej5(x,N,n);

% Graficas

% Señal de entrada

stemCompleto(n,x,...
  'AxisLimits',[n(1) n(length(n))  -5 5],...
  'Hold',1,...
  'Subplot',[2 1 1],...
  'XLabel','n',...
  'Title','Señal x[n]',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

legend('x[n]','location','northwest');

% Señal de salida

stemCompleto(n,y,...
  'AxisLimits',[n(1) n(length(n)) -5 9],...
  'Hold',1,...
  'Subplot',[2 1 2],...
  'XLabel','n',...
  'Title','Señal y[n]',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

legend('y[n]','location','northwest');


