%% Ej 7 P3 - IPS

clear all; close all; clc;

N1 = -3;
N2 = 3;

% Vector n = [-20 , -19 , ... , 19 , 20]
n = [N1:N2];

% Senal x[n] = 1 si |n| <=5
x = zeros(size(n)); x((n>=-5)&(n<=5)) = 1;

% III) Por ser un sistema Invariante al Desplazamiento
% si la entrada es desplazada K veces, la salida resulta
% desplazada K veces

% Desplazamiento K
K = 0;
x = circshift(x,[0,K]);

% Senal h[n] triangulo altura 10
h = zeros(size(n));

%  II) desde N1 a N2 es la ventana en la que se toma a las señales.
% Valores de N1 y N2 muy chicos acortan a las señales x y h y la
% convolución resultante queda más chica

% Modifiqué el intervalo que se toma del triangulo para cualquier N1 y N2
h((n>=-9)&(n<=9)) = [[((N1<=-9)*1 + (N1>-9)*(10 + N1)):1:10] [9:-1:(N2<9)*(10 - N2) + (N2>=9)*1]];

% Vector n2 = [-40 , -39 , ... , 39 , 40]
n2 = [2*n(1):2*n(length(n))];

% Senal producida de la convolucion entre x y h
y = conv(x,h);


% I)

stemCompleto(n,x,...
  'AxisLimits',[-12 12 -2 2],...
  'Hold',1,...
  'Subplot',[1 3 1],...
  'XLabel','n',...
  'Title','Señal x[n]',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

legend('x[n]','location','northwest');

stemCompleto(n,h,...
  'AxisLimits',[-12 12 -2 12],...
  'Hold',1,...
  'Subplot',[1 3 2],...
  'XLabel','n',...
  'Title','Señal h[n]',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

legend('h[n]','location','northwest');

stemCompleto(n2,y,...
  'AxisLimits',[-20 20 -2 100],...
  'Hold',1,...
  'Subplot',[1 3 3],...
  'XLabel','n',...
  'Title','Señal y[n] = {x*h}[n]',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

legend('y[n]','location','northwest');




