%% Ej 6 P1  -  AnSyS - IPS
% Limpiamos la ventana de comandos, borramos todas las variables, cerramos
% todas las figuras.
clear all;close all;clc;
% Añadimos directorio con definiciones de funciones útiles
addpath('../../funciones')
% Creamos un vector de tiempo útil para todo el ejercicio.
dt = 1e-3;
t  = -20:dt:20;

x  = tri1(t);

%% a)
xa = tri1(t+1);

plotCompleto(t,x,'Maximize',1);

plotCompleto(t,xa,...
    'Hold',1,...
    'AxisLimits',[-4 4 -1 3],...
    'XLabel','$t$',...
    'YLabel','$h(t+1)$',...
    'Title','Ej 6 a) - P1',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',2);

legend('$h(t)$','$h(t+1)$', 'Interpreter', 'latex')

%% b)
xb = tri1(2*t-3);

plotCompleto(t,x,'Maximize',1);

plotCompleto(t,xb,...
    'Hold',1,...
    'AxisLimits',[-4 4 -1 3],...
    'XLabel','$t$',...
    'YLabel','$h(2t-3)$',...
    'Title','Ej 6 b) - P1',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',2);

legend('$h(t)$','$h(2t-3)$', 'Interpreter', 'latex')

%% c)
xc = 2*tri1(-1/2*(t+10));

plotCompleto(t,x,'Maximize',1);

plotCompleto(t,xc,...
    'Hold',1,...
    'AxisLimits',[-20 5 -1 5],...
    'XLabel','$t$',...
    'YLabel','$2h(-1/2(t+10))$',...
    'Title','Ej 6 c) - P1',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',2);

legend('$h(t)$','$2h(-1/2(t+10))$', 'Interpreter', 'latex')

%% d)
xd = tri1(t/2).*(escalon(t+2) - escalon(t-2));

plotCompleto(t,x,'Maximize',1,'LineWidth',1);

plotCompleto(t,xd,...
    'Hold',1,...
    'AxisLimits',[-5 5 -1 3],...
    'XLabel','$t$',...
    'YLabel','$h(t/2)[u(t+2) - u(t-2)]$',...
    'Title','Ej 6 d) - P1',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',2);

legend('$h(t)$','$2h(-1/2(t+10))$', 'Interpreter', 'latex')

%% e)
xe = tri1(t.^2);

plotCompleto(t,x,'Maximize',1);

plotCompleto(t,xe,...
    'Hold',1,...
    'AxisLimits',[-5 5 -1 3],...
    'XLabel','$t$',...
    'YLabel','$h(t^2)$',...
    'Title','Ej 6 e) - P1',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',2);

legend('$h(t)$','$h(t^2)$', 'Interpreter', 'latex')

%% f)
xf = (tri1(t) - tri1(-t))/2;

plotCompleto(t,x,'Maximize',1);

plotCompleto(t,xf,...
    'Hold',1,...
    'AxisLimits',[-6 6 -2 2.5],...
    'XLabel','$t$',...
    'YLabel','$Impar\{h(t)\}$',...
    'Title','Ej 6 f) - P1',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',2);

legend('$h(t)$','$Impar\{h(t)\}$', 'Interpreter', 'latex')

%% g)
xg = (tri1(t) + tri1(-t))/2;

plotCompleto(t,x,'Maximize',1);

plotCompleto(t,xg,...
    'Hold',1,...
    'AxisLimits',[-6 6 -0.5 2.5],...
    'XLabel','$t$',...
    'YLabel','$Par\{h(t)\}$',...
    'Title','Ej 6 g) - P1',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',2);

legend('$h(t)$','$Par\{h(t)\}$', 'Interpreter', 'latex')
