% ---------------------------------------------------------
% Ejercicio 1 - Inciso 3
% Descripción breve: Implementación de los sistemas y graficos comparativos:
%-Respuesta impulsional obtenida analiticamente en comparacion con la salida de cada sistema al ingresar una deltaKronecker
%-TFTD de la respuesta impulsional obtenida analiticamente en comparacion con la aproximacion de la TFTD para cada respuesta impulsional
% ---------------------------------------------------------

function ejercicio01inc3()
% Carpeta donde está este archivo
baseDir = fileparts(mfilename('fullpath'));

% Funciones está DOS niveles arriba
funcDir = fullfile(baseDir, '..', '..', 'Funciones');
addpath(funcDir);

%Indice n para los que graficaremos cada h[n]
n=[-1:10];

%Indice s para los que graficaremos cada H(e^(j2pis))
S=0.5;
ds=1e-3;
s=[-S:ds:S];

%Respuesta impulsional de S1
[ny,h]=sistema1(n,deltaKronecker(n));

stemCompleto(ny,h,...
  'AxisLimits',[min(ny) max(ny) min(h)*1.2 max(h)*1.2],...
  'Hold',1,...
  'Subplot',[4 6 2],...
  'XLabel','n',...
  'YLabel','h_1[n]',...
  'Title','h[n] (Octave)',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

%Respuesta impulsional analitica de S1

h= 0.5 * deltaKronecker(n) + 0.5 * deltaKronecker(n-1);

stemCompleto(n,h,...
  'AxisLimits',[min(n) max(n) min(h)*1.2 max(h)*1.2],...
  'Hold',1,...
  'Subplot',[4 6 1],...
  'XLabel','n',...
  'YLabel','h_1[n]',...
  'Title','h[n] analitica',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

% TFTD Aproximación S1
H_aprox = zeros(size(s));
for i = 1:length(s)
  H_aprox(i) = sum(h.*exp(-1i*2*pi*s(i)*n));
end

plotCompleto(s,abs(H_aprox),...
    'Hold',1,...
    'Subplot',[4 6 4],...
    'AxisLimits',[min(s) max(s) min(abs(H_aprox))*1.2 max(abs(H_aprox))*1.2],...
    'XLabel','s',...
    'YLabel','|H_1(e^{j2πs})_a_p_r_o_x|',...
    'Title','Modulo de TFTD_a_p_r_o_x_i_m_a_d_a',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

plotCompleto(s,angle(H_aprox),...
    'Hold',1,...
    'Subplot',[4 6 6],...
    'AxisLimits',[min(s) max(s) min(angle(H_aprox))*1.2 max(angle(H_aprox))*1.2],...
    'XLabel','s',...
    'YLabel','∠H_1(e^{j2πs})_a_p_r_o_x',...
    'Title','Fase de TFTD_a_p_r_o_x_i_m_a_d_a',...
    'FontSize',20,...
    'LineStyle','r.-',...t
    'LineWidth',3);

% TFTD Analítica S1
H_ana=(0.5)*(1+exp(-1i*2*pi*s));

plotCompleto(s,abs(H_ana),...
    'Hold',1,...
    'Subplot',[4 6 3],...
    'AxisLimits',[min(s) max(s) min(abs(H_ana))*1.2 max(abs(H_ana))*1.2],...
    'XLabel','s',...
    'YLabel','|H_1(e^{j2πs})|',...
    'Title','Modulo de TFTD',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

plotCompleto(s,angle(H_ana),...
    'Hold',1,...
    'Subplot',[4 6 5],...
    'AxisLimits',[min(s) max(s) min(angle(H_ana))*1.2 max(angle(H_ana))*1.2],...
    'XLabel','s',...
    'YLabel','∠H_1(e^{j2πs})',...
    'Title','Fase de TFTD',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

%Respuesta impulsional de S2
[ny,h]=sistema2(n,deltaKronecker(n));

stemCompleto(ny,h,...
  'AxisLimits',[min(ny) max(ny) min(h)*1.2 max(h)*1.2],...
  'Hold',1,...
  'Subplot',[4 6 8],...
  'XLabel','n',...
  'YLabel','h_2[n]',...
  'Title','',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

%Respuesta impulsional analitica de S2

h=0.5 * deltaKronecker(n) - 0.5 * deltaKronecker(n-1);

stemCompleto(n,h,...
  'AxisLimits',[min(n) max(n) min(h)*1.2 max(h)*1.2],...
  'Hold',1,...
  'Subplot',[4 6 7],...
  'XLabel','n',...
  'YLabel','h_2[n]',...
  'Title','',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

% TFTD Aproximación S2
H_aprox = zeros(size(s));
for i = 1:length(s)
  H_aprox(i) = sum(h.*exp(-1i*2*pi*s(i)*n));
end

plotCompleto(s,abs(H_aprox),...
    'Hold',1,...
    'Subplot',[4 6 10],...
    'AxisLimits',[min(s) max(s) min(abs(H_aprox))*1.2 max(abs(H_aprox))*1.2],...
    'XLabel','s',...
    'YLabel','|H_2(e^{j2πs})_a_p_r_o_x|',...
    'Title','',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

plotCompleto(s,angle(H_aprox),...
    'Hold',1,...
    'Subplot',[4 6 12],...
    'AxisLimits',[min(s) max(s) min(angle(H_aprox))*1.2 max(angle(H_aprox))*1.2],...
    'XLabel','s',...
    'YLabel','∠H_2(e^{j2πs})_a_p_r_o_x',...
    'Title','',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

% TFTD Analítica S2
H_ana=(0.5)*(1-exp(-1i*2*pi*s));

plotCompleto(s,abs(H_ana),...
    'Hold',1,...
    'Subplot',[4 6 9],...
    'AxisLimits',[min(s) max(s) min(abs(H_ana))*1.2 max(abs(H_ana))*1.2],...
    'XLabel','s',...
    'YLabel','|H_2(e^{j2πs})|',...
    'Title','',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

plotCompleto(s,angle(H_ana),...
    'Hold',1,...
    'Subplot',[4 6 11],...
    'AxisLimits',[min(s) max(s) min(angle(H_ana))*1.2 max(angle(H_ana))*1.2],...
    'XLabel','s',...
    'YLabel','∠H_2(e^{j2πs})',...
    'Title','',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);


%Respuesta impulsional de S3
[ny,h]=sistema3(n,deltaKronecker(n));

stemCompleto(ny,h,...
  'AxisLimits',[min(ny) max(ny) min(h)*1.2 max(h)*1.2],...
  'Hold',1,...
  'Subplot',[4 6 14],...
  'XLabel','n',...
  'YLabel','h_3[n]',...
  'Title','',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

%Respuesta impulsional analitica de S3

h=(0.25)*(0.5).^n .*(escalon(n) + 2*escalon(n-1));

stemCompleto(n,h,...
  'AxisLimits',[min(n) max(n) min(h)*1.2 max(h)*1.2],...
  'Hold',1,...
  'Subplot',[4 6 13],...
  'XLabel','n',...
  'YLabel','h_3[n]',...
  'Title','',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

% TFTD Aproximación S3
H_aprox = zeros(size(s));
for i = 1:length(s)
  H_aprox(i) = sum(h.*exp(-1i*2*pi*s(i)*n));
end

plotCompleto(s,abs(H_aprox),...
    'Hold',1,...
    'Subplot',[4 6 16],...
    'AxisLimits',[min(s) max(s) min(abs(H_aprox))*1.2 max(abs(H_aprox))*1.2],...
    'XLabel','s',...
    'YLabel','|H_3(e^{j2πs})_a_p_r_o_x|',...
    'Title','',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

plotCompleto(s,unwrap(angle(H_aprox)),...
    'Hold',1,...
    'Subplot',[4 6 18],...
    'AxisLimits',[min(s) max(s) min(unwrap(angle(H_aprox)))*1.2 max(unwrap(angle(H_aprox)))*1.2],...
    'XLabel','s',...
    'YLabel','∠H_3(e^{j2πs})_a_p_r_o_x',...
    'Title','',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

% TFTD Analítica S3

H_ana=((0.25).*(1 ./ (1-0.5*exp(-1i*2*pi*s)))).* (1+exp(-1i*2*pi*s));

plotCompleto(s,abs(H_ana),...
    'Hold',1,...
    'Subplot',[4 6 15],...
    'AxisLimits',[min(s) max(s) min(abs(H_ana))*1.2 max(abs(H_ana))*1.2],...
    'XLabel','s',...
    'YLabel','|H_3(e^{j2πs})|',...
    'Title','',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

plotCompleto(s,unwrap(angle(H_ana)),...
    'Hold',1,...
    'Subplot',[4 6 17],...
    'AxisLimits',[min(s) max(s) min(unwrap(angle(H_ana)))*1.2 max(unwrap(angle(H_ana)))*1.2],...
    'XLabel','s',...
    'YLabel','∠H_3(e^{j2πs})',...
    'Title','',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);


%Respuesta impulsional de S4
[ny,h]=sistema4(n,deltaKronecker(n));

stemCompleto(ny,h,...
  'AxisLimits',[min(ny) max(ny) min(h)*1.2 max(h)*1.2],...
  'Hold',1,...
  'Subplot',[4 6 20],...
  'XLabel','n',...
  'YLabel','h_4[n]',...
  'Title','',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

%Respuesta impulsional analitica de S4

h= (0.25)*(-0.5).^n .*(escalon(n) + 2*escalon(n-1));

stemCompleto(n,h,...
  'AxisLimits',[min(n) max(n) min(h)*1.2 max(h)*1.2],...
  'Hold',1,...
  'Subplot',[4 6 19],...
  'XLabel','n',...
  'YLabel','h_4[n]',...
  'Title','',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

% TFTD Aproximación S4
H_aprox = zeros(size(s));
for i = 1:length(s)
  H_aprox(i) = sum(h.*exp(-1i*2*pi*s(i)*n));
end

plotCompleto(s,abs(H_aprox),...
    'Hold',1,...
    'Subplot',[4 6 22],...
    'AxisLimits',[min(s) max(s) min(abs(H_aprox))*1.2 max(abs(H_aprox))*1.2],...
    'XLabel','s',...
    'YLabel','|H_4(e^{j2πs})_a_p_r_o_x|',...
    'Title','',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

plotCompleto(s,unwrap(angle(H_aprox)),...
    'Hold',1,...
    'Subplot',[4 6 24],...
    'AxisLimits',[min(s) max(s) min(unwrap(angle(H_aprox)))*1.2 max(unwrap(angle(H_aprox)))*1.2],...
    'XLabel','s',...
    'YLabel','∠H_4(e^{j2πs})_a_p_r_o_x',...
    'Title','',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

% TFTD Analítica S4

H_ana=((0.25).*(1 ./ (1+0.5*exp(-1i*2*pi*s)))).* (1-exp(-1i*2*pi*s));

plotCompleto(s,abs(H_ana),...
    'Hold',1,...
    'Subplot',[4 6 21],...
    'AxisLimits',[min(s) max(s) min(abs(H_ana))*1.2 max(abs(H_ana))*1.2],...
    'XLabel','s',...
    'YLabel','|H_4(e^{j2πs})|',...
    'Title','',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

plotCompleto(s,unwrap(angle(H_ana)),...
    'Hold',1,...
    'Subplot',[4 6 23],...
    'AxisLimits',[min(s) max(s) min(unwrap(angle(H_ana)))*1.2 max(unwrap(angle(H_ana)))*1.2],...
    'XLabel','s',...
    'YLabel','∠H_4(e^{j2πs})',...
    'Title','',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);


end
