% ---------------------------------------------------------
% Ejercicio 1 - Inciso 1
% Descripción breve: Grafico de senial.m y  de la aproximación de su TFTD
% ---------------------------------------------------------

function ejercicio01inc1 ()

% Carpeta donde está este archivo
baseDir = fileparts(mfilename('fullpath'));

% Funciones está DOS niveles arriba
funcDir = fullfile(baseDir, '..', '..', 'Funciones');
addpath(funcDir);
% IPS2025_PU1 está UN nivel arriba
labDir = fullfile(baseDir, '..', 'IPS2025_PU1');
addpath(labDir);

% Limpiar todo
clear all; close all; clc;

%Obtención de indices para los que esta definida senial.m junto con la salida para cada uno de esos n
[n , x] = senial(37514);

% Índice de frecuencia s para la aproximacion de la TFTD
S = 0.5;
ds = 1e-3;
s = -S:ds:S;

% Aproximación TFTD

X_aprox = zeros(size(s));
for k = 1:length(s)
  X_aprox(k) = sum(x.*exp(-1i*2*pi*s(k)*n));
end;


stemCompleto(n,real(x),...
  %'Hold',1,...
  %'Subplot',[3 1 1],...
  'AxisLimits',[min(n) max(n) min(x)*1.2 max(x)*1.2],...
  'XLabel','n',...
  %'Title','Señal x[n] = senial(37514)',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

legend('real(x[n])','location','northwest');


stemCompleto(n,imag(x),...
  %'Hold',1,...
  %'Subplot',[3 1 1],...
  'AxisLimits',[min(n) max(n) -1 1],...
  'XLabel','n',...
  %'Title','Señal x[n] = senial(37514)',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','b',...
  'MarkerFaceColor','b',...
  'MarkerEdgeColor','b',...
  'LineWidth',3);

legend('imag(x[n])','location','northwest');


plotCompleto(s,abs(X_aprox),...
    %'Hold',1,...
    %'Subplot',[2 1 1],...
    'AxisLimits',[-S S min(abs(X_aprox))*1.2 max(abs(X_aprox))*1.2],...
    'XLabel','s',...
    %'Title','TFTD aprox de senial',...
    'FontSize',20,...
    'LineStyle','p.-',...
    'LineWidth',3);

legend('abs(X_a_p_r_o_x)','location','northwest');

plotCompleto(s,unwrap(angle(X_aprox)),...
    %'Hold',1,...
    %'Subplot',[2 1 2],...
    'AxisLimits',[-S S min(unwrap(angle(X_aprox)))*1.2 max(unwrap(angle(X_aprox)))*1.2],...
    'XLabel','s',...
    %'Title','TFTD aprox de senial',...
    'FontSize',20,...
    'LineStyle','b.-',...
    'LineWidth',3);

legend('angle(X_a_p_r_o_x)','location','northwest');

end
