% ---------------------------------------------------------
% Ejercicio 1 - Inciso 2
% Descripción breve: Graficos de la respuesta impulsional y la respuesta en frecuencia de cada uno de los sistemas (de manera analítica).
% ---------------------------------------------------------

function ejercicio01inc2 ()

% Carpeta donde está este archivo
baseDir = fileparts(mfilename('fullpath'));

% Funciones está DOS niveles arriba
funcDir = fullfile(baseDir, '..', '..', 'Funciones');
addpath(funcDir);


%Indice n para los que graficaremos cada h[n]
n=[-1:10];

%Indice s para los que graficaremos cada H(e^(j2pis))

S=0.5;
ds=1e-3;
s=[-S:ds:S];

%-----Sistema 1-----

h=0.5 .* deltaKronecker(n)+ 0.5 .* deltaKronecker(n-1);

stemCompleto(n,h,...
  'AxisLimits',[min(n) max(n) min(h)*1.2 max(h)*1.2],...
  'Hold',1,...
  'Subplot',[4 3 1],...
  'XLabel','n',...
  'YLabel','h_1[n]',...
  'Title','Respuesta impulsional',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);


H=(0.5).*(1+exp(-1i*2*pi*s));

plotCompleto(s,abs(H),...
    'Hold',1,...
    'Subplot',[4 3 2],...
    'AxisLimits',[min(s) max(s) min(H)*1.2 max(H)*1.2],...
    'XLabel','s',...
    'YLabel','|H_1(e^{j2πs})|',...
    'Title','Modulo de respuesta en frecuencia (|s| <= 1/2)',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

plotCompleto(s,angle(H),...
    'Hold',1,...
    'Subplot',[4 3 3],...
    'AxisLimits',[min(s) max(s) min(angle(H))*1.2 max(angle(H))*1.2],...
    'XLabel','s',...
    'YLabel', '∠H_1(e^{j2πs})',...
    'Title','Fase de respuesta en frecuencia (|s| <= 1/2)',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

%-----Sistema 2-----

h=0.5 .* deltaKronecker(n) - 0.5 .* deltaKronecker(n-1);

stemCompleto(n,h,...
  'AxisLimits',[min(n) max(n) min(h)*1.2 max(h)*1.2],...
  'Hold',1,...
  'Subplot',[4 3 4],...
  'XLabel','n',...
  'YLabel','h_2[n]',...
  'Title','',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);


H=(0.5).*(1-exp(-1i*2*pi*s));

plotCompleto(s,abs(H),...
    'Hold',1,...
    'Subplot',[4 3 5],...
    'AxisLimits',[min(s) max(s) min(H)*1.2 max(H)*1.2],...
    'XLabel','s',...
    'YLabel','|H_2(e^{j2πs})|',...
    'Title','',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

plotCompleto(s,angle(H),...
    'Hold',1,...
    'Subplot',[4 3 6],...
    'AxisLimits',[min(s) max(s) min(angle(H))*1.2 max(angle(H))*1.2],...
    'XLabel','s',...
    'YLabel', '∠H_2(e^{j2πs})',...
    'Title','',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

%-----Sistema 3-----

h=0.25*(0.5).^n.*(escalon(n) + 2*escalon(n-1));

stemCompleto(n,h,...
  'AxisLimits',[min(n) max(n) min(h)*1.2 max(h)*1.2],...
  'Hold',1,...
  'Subplot',[4 3 7],...
  'XLabel','n',...
  'YLabel','h_3[n]',...
  'Title','',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);


H=( (0.25).*(1 ./ (1-0.5*exp(-1i*2*pi*s)))).*(1+exp(-1i*2*pi*s));

plotCompleto(s,abs(H),...
    'Hold',1,...
    'Subplot',[4 3 8],...
    'AxisLimits',[min(s) max(s) min(H)*1.2 max(H)*1.2],...
    'XLabel','s',...
    'YLabel','|H_3(e^{j2πs})|',...
    'Title','',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);


plotCompleto(s,angle(H),...
    'Hold',1,...
    'Subplot',[4 3 9],...
    'AxisLimits',[min(s) max(s) min(angle(H))*1.2 max(angle(H))*1.2],...
    'XLabel','s',...
    'YLabel','∠H_3(e^{j2πs})',...
    'Title','',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);


%-----Sistema 4------

h=0.25*(-0.5).^n.*(escalon(n) + 2*escalon(n-1));

stemCompleto(n,h,...
  'AxisLimits',[min(n) max(n) min(h)*1.2 max(h)*1.2],...
  'Hold',1,...
  'Subplot',[4 3 10],...
  'XLabel','n',...
  'YLabel','h_4[n]',...
  'Title','',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

%legend('h3[n]','location','northwest');


H=( (0.25).*(1 ./ (1+0.5*exp(-1i*2*pi*s)))).*(1-exp(-1i*2*pi*s));

plotCompleto(s,abs(H),...
    'Hold',1,...
    'Subplot',[4 3 11],...
    'AxisLimits',[min(s) max(s) min(H)*1.2 max(H)*1.2],...
    'XLabel','s',...
    'YLabel','|H_4(e^{j2πs})|',...
    'Title','',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

%legend('|H(e^{j2\pis})|','location','northwest');

plotCompleto(s,angle(H),...
    'Hold',1,...
    'Subplot',[4 3 12],...
    'AxisLimits',[min(s) max(s) min(angle(H))*1.2 max(angle(H))*1.2],...
    'XLabel','s',...
    'YLabel','∠H_4(e^{j2πs})',...
    'Title','',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

%legend('∠H(e^{j2\pis})','location','northwest');


end
