% ---------------------------------------------------------
% Ejercicio 1 - Inciso 4
% Descripción breve: Graficos de la señal de salida para cada sistema, cuando se aplica a la entrada la señal del inciso 1.
% ---------------------------------------------------------

function ejercicio01inc4 ()
% Carpeta donde está este archivo
baseDir = fileparts(mfilename('fullpath'));

% Funciones está DOS niveles arriba
funcDir = fullfile(baseDir, '..', '..', 'Funciones');
addpath(funcDir);
%IPS2025_PU1 está UN nivel arriba
labDir = fullfile(baseDir, '..', 'IPS2025_PU1');
addpath(labDir);

% Crear el nombre del archivo de salida dentro del mismo directorio
outputFile = fullfile(baseDir, 'salidasinc4.mat');

%Obtención de indices para los que esta definida senial.m junto con la salida para cada uno de esos n
[n, x] = senial(038528);

%Salida al ingresarle al sistema 1 la senial.m
y1=sistema1(x);

stemCompleto(n,y1,...
  'AxisLimits',[min(n) max(n) min(y1)*1.2 max(y1)*1.2],...
  'Hold',1,...
  'Subplot',[4 1 1],...
  'XLabel','n',...
  'YLabel','y_1[n]',...
  'Title','Salida de S1 al aplicar senial.m',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

%Salida al ingresarle al sistema 2 la senial.m
y2=sistema2(x);

stemCompleto(n,y2,...
  'AxisLimits',[min(n) max(n) min(y2)*1.2 max(y2)*1.2],...
  'Hold',1,...
  'Subplot',[4 1 2],...
  'XLabel','n',...
  'YLabel','y_2[n]',...
  'Title','Salida de S2 al aplicar senial.m',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

%Salida al ingresarle al sistema 3 la senial.m
y3=sistema3(x);

stemCompleto(n,y3,...
  'AxisLimits',[min(n) max(n) min(y3)*1.2 max(y3)*1.2],...
  'Hold',1,...
  'Subplot',[4 1 3],...
  'XLabel','n',...
  'YLabel','y_3[n]',...
  'Title','Salida de S3 al aplicar senial.m',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

%Salida al ingresarle al sistema 4 la senial.m
y4=sistema4(x);

stemCompleto(n,y4,...
  'AxisLimits',[min(n) max(n) min(y4)*1.2 max(y4)*1.2],...
  'Hold',1,...
  'Subplot',[4 1 4],...
  'XLabel','n',...
  'YLabel','y_4[n]',...
  'Title','Salida de S4 al aplicar senial.m',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

save(outputFile, 'n', 'y1', 'y2', 'y3', 'y4');


  end
