
function ejercicio01inc5 ()
if ~exist('salidasinc4.mat', 'file')
     fprintf("⚠️Primero ejecute el inciso 4. No se encontraron las salidas.\n");
     disp("Presione una tecla para volver al menú del ejercicio 1...");
     pause;
    return;
end
% Obtener la ruta del directorio del inciso 5
baseDir = fileparts(mfilename('fullpath'));
% Funciones está DOS niveles arriba
funcDir = fullfile(baseDir, '..', '..', 'Funciones');
addpath(funcDir);
% Crear el path al archivo de salidas
inputFile = fullfile(baseDir, 'salidasinc4.mat');

% Cargar las variables
load(inputFile);



%Indice s para los que graficaremos cada Y(e^(j2pis))

S=0.5;
ds=1e-3;
s=[-S:ds:S];

%Aproximación de la TFTD de la salida del sistema 1 al ingresar senial.m
Y_aprox = zeros(size(s));
for i = 1:length(s)
  Y_aprox(i) = sum(y1.*exp(-1i*2*pi*s(i)*n1));
end

plotCompleto(s,abs(Y_aprox),...
    'Hold',1,...
    'Subplot',[4 2 1],...
    'AxisLimits',[min(s) max(s) min(abs(Y_aprox))*1.2 max(abs(Y_aprox))*1.2],...
    'XLabel','s',...
    'YLabel','|Y_1(e^{j2πs})_a_p_r_o_x|',...
    'Title','Modulo de TFTD_a_p_r_o_x ',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

plotCompleto(s,unwrap(angle(Y_aprox)),...
    'Hold',1,...
    'Subplot',[4 2 2],...
    'AxisLimits',[min(s) max(s) min(unwrap(angle(Y_aprox)))*1.2 max(unwrap(angle(Y_aprox)))*1.2],...
    'XLabel','s',...
    'YLabel','∠Y_1(e^{j2πs})_a_p_r_o_x',...
    'Title','Fase de TFTD_a_p_r_o_x ',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

%Aproximación de la TFTD de la salida del sistema 2 al ingresar senial.m
Y_aprox = zeros(size(s));
for i = 1:length(s)
  Y_aprox(i) = sum(y2.*exp(-1i*2*pi*s(i)*n2));
end

plotCompleto(s,abs(Y_aprox),...
    'Hold',1,...
    'Subplot',[4 2 3],...
    'AxisLimits',[min(s) max(s) min(abs(Y_aprox))*1.2 max(abs(Y_aprox))*1.2],...
    'XLabel','s',...
    'YLabel','|Y_2(e^{j2πs})_a_p_r_o_x|',...
    'Title',' ',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

plotCompleto(s,unwrap(angle(Y_aprox)),...
    'Hold',1,...
    'Subplot',[4 2 4],...
    'AxisLimits',[min(s) max(s) min(unwrap(angle(Y_aprox)))*1.2 max(unwrap(angle(Y_aprox)))*1.2],...
    'XLabel','s',...
    'YLabel','∠Y_2(e^{j2πs})_a_p_r_o_x',...
    'Title','',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

%Aproximación de la TFTD de la salida del sistema 3 al ingresar senial.m
Y_aprox = zeros(size(s));
for i = 1:length(s)
  Y_aprox(i) = sum(y3.*exp(-1i*2*pi*s(i)*n3));
end

plotCompleto(s,abs(Y_aprox),...
    'Hold',1,...
    'Subplot',[4 2 5],...
    'AxisLimits',[min(s) max(s) min(abs(Y_aprox))*1.2 max(abs(Y_aprox))*1.2],...
    'XLabel','s',...
    'YLabel','|Y_3(e^{j2πs})_a_p_r_o_x|',...
    'Title','',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

plotCompleto(s,unwrap(angle(Y_aprox)),...
    'Hold',1,...
    'Subplot',[4 2 6],...
    'AxisLimits',[min(s) max(s) min(unwrap(angle(Y_aprox)))*1.2 max(unwrap(angle(Y_aprox)))*1.2],...
    'XLabel','s',...
    'YLabel','∠Y_3(e^{j2πs})_a_p_r_o_x',...
    'Title','',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

%Aproximación de la TFTD de la salida del sistema 4 al ingresar senial.m
Y_aprox = zeros(size(s));
for i = 1:length(s)
  Y_aprox(i) = sum(y4.*exp(-1i*2*pi*s(i)*n4));
end

plotCompleto(s,abs(Y_aprox),...
    'Hold',1,...
    'Subplot',[4 2 7],...
    'AxisLimits',[min(s) max(s) min(abs(Y_aprox))*1.2 max(abs(Y_aprox))*1.2],...
    'XLabel','s',...
    'YLabel','|Y_4(e^{j2πs})_a_p_r_o_x|',...
    'Title','',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);

plotCompleto(s,unwrap(angle(Y_aprox)),...
    'Hold',1,...
    'Subplot',[4 2 8],...
    'AxisLimits',[min(s) max(s) min(unwrap(angle(Y_aprox)))*1.2 max(unwrap(angle(Y_aprox)))*1.2],...
    'XLabel','s',...
    'YLabel','∠Y_4(e^{j2πs})_a_p_r_o_x',...
    'Title','',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);


end
