addpath('Laboratorio1/IPS2025_PU1');
addpath('Funciones');

clear all; close all; clc;

[n, h] = hcanald(037514);



stemCompleto(n,h,...
  'AxisLimits',[min(n) max(n) min(h)*1.2 max(h)*1.2],...
  'Hold',1,...
  'Subplot',[2 1 1],...
  'XLabel','n',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

for i = 1:length(n)
  if h(i) != 0
    disp(n(i));
    disp(h(i));
  endif
end
%{
0
8820
17640

%}

h_2 = sistema(deltaKronecker(n));

stemCompleto(n,h_2,...
  'AxisLimits',[min(n) max(n) min(h)*1.2 max(h)*1.2],...
  'Hold',1,...
  'Subplot',[2 1 2],...
  'XLabel','n',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

