function ejercicio02inc3 ()

clear all; close all; clc;
% Carpeta donde está este archivo
baseDir = fileparts(mfilename('fullpath'));
% Funciones está DOS niveles arriba
funcDir = fullfile(baseDir, '..', '..', 'Funciones');
addpath(funcDir);
%IPS2025_PU1 está UN nivel arriba
labDir = fullfile(baseDir, '..', 'IPS2025_PU1');
addpath(labDir);
audioDir = fullfile(labDir,'audio.wav');

[z , fs] = audioread(audioDir); %Devuelve en z una matriz de 2 columnas dado que el audio es estereo
x1 = (z(:,1)).'; %Toma la primera columna (z(:,1) es un vector columna) → canal izquierdo. Luego .' lo transpone → lo convierte en vector fila.
x2 = (z(:,2)).'; %Mismo con canal derecho
x = (x1+x2)/2; %Promedio obteniendo audio mono

n = 1:length(x);

plotCompleto(n,x1,...
    'Hold',1,...
    'Subplot',[4 1 1 ],...
    'AxisLimits',[min(n) max(n) min(x1)*1.2 max(x1)*1.2],...
    'XLabel','',...
    'Title','Canal izquierdo',...
    'FontSize',20,...
    'LineStyle','b.-',...
    'LineWidth',3);



plotCompleto(n,x2,...
    'Hold',1,...
    'Subplot',[4 1 2 ],...
    'AxisLimits',[min(n) max(n) min(x2)*1.2 max(x2)*1.2],...
    'XLabel','',...
    'Title','Canal derecho',...
    'FontSize',20,...
    'LineStyle','b.-',...
    'LineWidth',3);


plotCompleto(n,x,...
    'Hold',1,...
    'Subplot',[4 1 3 ],...
    'AxisLimits',[min(n) max(n) min(x)*1.2 max(x)*1.2],...
    'XLabel','',...
    'Title','Audio mono',...
    'FontSize',20,...
    'LineStyle','b.-',...
    'LineWidth',3);


[ny,y] = canal(n,x);


plotCompleto(ny,y,...
    'Hold',1,...
    'AxisLimits',[min(ny) max(ny) min(y)*1.2 max(y)*1.2],...
    'Subplot',[4 1 4],...
    'XLabel','',...
    'Title','Salida del sistema para audio.wav',...
    'FontSize',20,...
    'LineStyle','b.-',...
    'LineWidth',3);
end
