function ejercicio02inc4 ()
clear all; close all; clc;
% Carpeta donde está este archivo
baseDir = fileparts(mfilename('fullpath'));
% Funciones está DOS niveles arriba
funcDir = fullfile(baseDir, '..', '..', 'Funciones');
addpath(funcDir);

%n arbitrario para generar la deltaKronecker
n=[-5:5];
%Respuesta impulsional del canal
[nh,hCanal]=canal(n,deltaKronecker(n));


%Respuesta impulsional total al aplicarle en cascada el filtro con 1 rama de retardo
[ny,hTot]=filtro1(nh,hCanal);

stemCompleto(ny,hTot,...
  'AxisLimits',[min(ny) max(ny) min(hTot)*1.2 max(hTot)*1.2],...
  'Hold',1,...
  'Subplot',[3 1 1],...
  'XLabel','n',...
  'YLabel','h_1[n]_t_o_t_a_l',...
  'Title','Respuesta impulsional Canal + Filtro1',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','y',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);


%Respuesta impulsional total al aplicarle en cascada el filtro con 2 rama de retardo
[ny,hTot]=filtro2(nh,hCanal);

stemCompleto(ny,hTot,...
  'AxisLimits',[min(ny) max(ny) min(hTot)*1.2 max(hTot)*1.2],...
  'Hold',1,...
  'Subplot',[3 1 2],...
  'XLabel','n',...
  'YLabel','h_2[n]_t_o_t_a_l',...
  'Title','Respuesta impulsional Canal + Filtro2',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','y',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);


%Respuesta impulsional total al aplicarle en cascada el filtro con 3 rama de retardo
[ny,hTot]=filtro3(nh,hCanal);

stemCompleto(ny,hTot,...
  'AxisLimits',[min(ny) max(ny) min(hTot)*1.2 max(hTot)*1.2],...
  'Hold',1,...
  'Subplot',[3 1 3],...
  'XLabel','n',...
  'YLabel','h_3[n]_t_o_t_a_l',...
  'Title','Respuesta impulsional Canal + Filtro3',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','y',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

end

