function ejercicio02inc2 ()

clear all; close all; clc;
% Carpeta donde está este archivo
baseDir = fileparts(mfilename('fullpath'));
% Funciones está DOS niveles arriba
funcDir = fullfile(baseDir, '..', '..', 'Funciones');
addpath(funcDir);


[n, h] = hcanald(037514);
%Salida del sistema implementado en como ecuacion en diferencias al aplicarle una delta de kronecker (Respuesta impulsional)
[ny,h] = canal(n,deltaKronecker(n));

stemCompleto(ny,h,...
  'AxisLimits',[min(ny) max(ny) min(h)*1.2 max(h)*1.2],...
  'Hold',1,...
  %'Subplot',[2 1 2],...
  'XLabel','n',...
  'YLabel','h[n]',...
  'Title','h[n] (Octave)',... %!!Con octave nos referimos a que es la salida del sistema implementado al ingresar una delta de kronecker!!
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);
end
