addpath('Funciones');

clear all; close all; clc;

[z , fs] = audioread('Laboratorio1/IPS2025_PU1/audio.wav');
x1 = (z(:,1)).';
x2 = (z(:,2)).';
x = (x1+x2)/2;

n = 1:length(x1);

%{
stemCompleto(n,x,...
  'AxisLimits',[min(n) max(n) min(x)*1.2 max(x)*1.2],...
  'XLabel','n',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);
%}

plotCompleto(n,x1,...
    'Hold',1,...
    'Subplot',[3 1 1 ],...
    'AxisLimits',[min(n) max(n) min(x1)*1.2 max(x1)*1.2],...
    'XLabel','s',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',3);



plotCompleto(n,x2,...
    'Hold',1,...
    'Subplot',[3 1 2 ],...
    'AxisLimits',[min(n) max(n) min(x2)*1.2 max(x2)*1.2],...
    'XLabel','s',...
    'FontSize',20,...
    'LineStyle','b.-',...
    'LineWidth',3);


plotCompleto(n,x,...
    'Hold',1,...
    'Subplot',[3 1 3 ],...
    'AxisLimits',[min(n) max(n) min(x)*1.2 max(x)*1.2],...
    'XLabel','s',...
    'FontSize',20,...
    'LineStyle','b.-',...
    'LineWidth',3);


y = sistema(x);


plotCompleto(n,y,...
    'AxisLimits',[min(n) max(n) min(y)*1.2 max(y)*1.2],...
    'XLabel','s',...
    'FontSize',20,...
    'LineStyle','b.-',...
    'LineWidth',3);

