addpath('Laboratorio1/IPS2025_PU1');
addpath('Funciones');

[n, x] = senial(038528);
y=sistema1(x);

stemCompleto(n,y,...
  'AxisLimits',[min(n) max(n) min(y)*1.2 max(y)*1.2],...
  'Hold',1,...
  'Subplot',[4 1 1],...
  'XLabel','x',...
  'YLabel','y_1[n]',...
  'Title','Salida de S1 al aplicar senial.m',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

y=sistema2(x);

stemCompleto(n,y,...
  'AxisLimits',[min(n) max(n) min(y)*1.2 max(y)*1.2],...
  'Hold',1,...
  'Subplot',[4 1 2],...
  'XLabel','x',...
  'YLabel','y_2[n]',...
  'Title','Salida de S2 al aplicar senial.m',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

y=sistema3(x);

stemCompleto(n,y,...
  'AxisLimits',[min(n) max(n) min(y)*1.2 max(y)*1.2],...
  'Hold',1,...
  'Subplot',[4 1 3],...
  'XLabel','x',...
  'YLabel','y_3[n]',...
  'Title','Salida de S3 al aplicar senial.m',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

y=sistema4(x);

stemCompleto(n,y,...
  'AxisLimits',[min(n) max(n) min(y)*1.2 max(y)*1.2],...
  'Hold',1,...
  'Subplot',[4 1 4],...
  'XLabel','x',...
  'YLabel','y_4[n]',...
  'Title','Salida de S4 al aplicar senial.m',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);
