addpath('Funciones');
addpath('Laboratorio1/IPS2025_PU1');

% Limpiar todo
clear all; close all; clc;

[n , x] = senial(37514);

% Índice de frecuencia s
S = 2;
ds = 1e-3;
s = -S:ds:S;

% Aproximación TFTD

X_aprox = zeros(size(s));
for k = 1:length(s)
  X_aprox(k) = sum(x.*exp(-1i*2*pi*s(k)*n));
end;

stemCompleto(n,real(x),...
  'Hold',1,...
  'Subplot',[3 1 1],...
  'AxisLimits',[min(n) max(n) min(x)*1.2 max(x)*1.2],...
  'XLabel','n',...
  'Title','Señal x[n] = senial(37514)',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

legend('x[n]','location','northwest');


plotCompleto(s,abs(X_aprox),...
    'Hold',1,...
    'Subplot',[3 1 2],...
    'AxisLimits',[-S S min(abs(X_aprox))*1.2 max(abs(X_aprox))*1.2],...
    'XLabel','s',...
    'Title','TFTD aprox de senial',...
    'FontSize',20,...
    'LineStyle','b.-',...
    'LineWidth',3);

legend('abs(X_aprox)','location','northwest');

plotCompleto(s,angle(X_aprox),...
    'Hold',1,...
    'Subplot',[3 1 3],...
    'AxisLimits',[-S S min(angle(X_aprox))*1.2 max(angle(X_aprox))*1.2],...
    'XLabel','s',...
    'Title','TFTD aprox de senial',...
    'FontSize',20,...
    'LineStyle','y.-',...
    'LineWidth',3);

legend('abs(X_aprox)','location','northwest');
