%% Ej 6 P1 - IPS
% Limpiamos la ventana de comandos, borramos todas las variables, cerramos
% todas las figuras.
clear all;close all;clc;
% Anadimos directorio con definiciones de funciones utiles
addpath('Funciones')
% Creamos un vector util para todo el ejercicio.
n = -5:5;

x = escalon(n) - escalon(n-5);



stemCompleto(n,x,...
  'AxisLimits',[-5 5 -3 3],...
  'XLabel','n',...
  'Title','Ej 6 b) - P1',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

legend('x[n]','location','northwest');


