%% Ej 6 P1 - IPS
% Limpiar
clear all; clc; close all;

addpath('Funciones');

%% Vectores a utilizar en todo el ejercicio

% VIC
dt = 1e-3
t = -30:dt:30;
% VID
n = -50:50;

% a)
xa = -2.*sin(-0.2.*t + (5/3).*pi);

plotCompleto(t,xa,...
  'AxisLimits',[-20 20 -3 3],...
  'XLabel','t',...
  'Title','a)',...
  'FontSize',20,...
  'LineStyle','r-',...
  'LineWidth',2);

% b)
xb = -2.*sin(-0.2.*n + (5/3).*pi);

stemCompleto(n,xb,...
  'AxisLimits',[-20 20 -3 3],...
  'XLabel','n',...
  'Title','b)',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

% c)
xc = (1/2).*(cos(2.*t - pi/4)).^2

plotCompleto(t,xc,...
  'AxisLimits',[-20 20 -1 1],...
  'XLabel','t',...
  'Title','c)',...
  'FontSize',20,...
  'LineStyle','r-',...
  'LineWidth',2);

% d)
xd = exp( j.*( (pi/2).*(t) - pi ) );
fased = atan2(imag(xd), real(xd));

% Parte real
plotCompleto(t,real(xd),...
  'AxisLimits',[-10 10 -2 2],...
  'Hold',1,...
  'Subplot',[3 1 1],...
  'XLabel','t',...
  'Title','d) Parte real',...
  'FontSize',20,...
  'LineStyle','r-',...
  'LineWidth',2);

% Parte imaginaria
plotCompleto(t,imag(xd),...
  'AxisLimits',[-10 10 -2 2],...
  'Hold',1,...
  'Subplot',[3 1 2],...
  'XLabel','t',...
  'Title','d) Parte imaginaria',...
  'FontSize',20,...
  'LineStyle','r-',...
  'LineWidth',2);

% Fase
plotCompleto(t,fased,...
  'AxisLimits',[-10 10 -5 5],...
  'Hold',1,...
  'Subplot',[3 1 3],...
  'XLabel','t',...
  'Title','d) Fase',...
  'FontSize',20,...
  'LineStyle','r-',...
  'LineWidth',2);

% e)
xe = exp( j.*( (1/2).*(n) - pi ) );
fasee = atan2(imag(xe), real(xe));

% Parte real
stemCompleto(n,real(xe),...
  'AxisLimits',[-20 20 -2 2],...
  'Hold',1,...
  'Subplot',[3 1 1],...
  'XLabel','n',...
  'Title','e) Parte real',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

% Parte imaginaria
stemCompleto(n,imag(xe),...
  'AxisLimits',[-20 20 -2 2],...
  'Hold',1,...
  'Subplot',[3 1 2],...
  'XLabel','n',...
  'Title','e) Parte imaginaria',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

% Fase
stemCompleto(n,fasee,...
  'AxisLimits',[-20 20 -5 5],...
  'Hold',1,...
  'Subplot',[3 1 3],...
  'XLabel','n',...
  'Title','e) Fase',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

% Lo dejo aca


