%% Ej 6 P1 - IPS
% Limpiamos la ventana de comandos, borramos todas las variables, cerramos
% todas las figuras.
clear all;close all;clc;
% Anadimos directorio con definiciones de funciones utiles
addpath('Funciones')
% Creamos un vector de tiempo util para todo el ejercicio.
dt = 1e-3;
t  = -20:dt:20;

x = tri1(t);

% a)
xa = tri1(t+1);

plotCompleto(t,x,'Subplot',[3 3 1],'Hold',1,'Maximize',1);

plotCompleto(t,xa, ...
    'Hold',1,...
    'Subplot',[3 3 1],...
    'AxisLimits',[-4 4 -1 3],...
    'XLabel','t',...
    %'YLabel','h(t+1)',...
    'Title','Ej 6 a) - P1',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',2);

legend('h(t)','h(t+1)','location','northwest');

%% b)
xb = tri1(2*t-3);

plotCompleto(t,x,'Subplot',[3 3 2],'Hold',1,'Maximize',1);

plotCompleto(t,xb,...
    'Hold',1,...
    'Subplot',[3 3 2],...
    'AxisLimits',[-4 4 -1 3],...
    'XLabel','t',...
    %'YLabel','h(2t-3)',...
    'Title','Ej 6 b) - P1',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',2);

legend('h(t)','h(2t-3)','location','northwest');

%% c)
xc = 2*tri1(-1/2*(t+10));

plotCompleto(t,x,'Subplot',[3 3 3],'Hold',1,'Maximize',1);

plotCompleto(t,xc,...
    'Hold',1,...
    'Subplot',[3 3 3],...
    'AxisLimits',[-20 5 -1 5],...
    'XLabel','t',...
    %'YLabel','$2h(-1/2(t+10))$',...
    'Title','Ej 6 c) - P1',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',2);

legend('h(t)','2h(-1/2(t+10))','location','northwest');

%% d)
xd = tri1(t/2).*(escalon(t+2) - escalon(t-2));

plotCompleto(t,x,'Subplot',[3 3 4],'Hold',1,'Maximize',1);

plotCompleto(t,xd,...
    'Hold',1,...
    'Subplot',[3 3 4],...
    'AxisLimits',[-5 5 -1 3],...
    'XLabel','t',...
    %'YLabel','$h(t/2)[u(t+2) - u(t-2)]$',...
    'Title','Ej 6 d) - P1',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',2);

legend('h(t)','h(t/2).[u(t+2)-u(t-2)]','location','northwest');

%% e)
xe = tri1(t.^2);

plotCompleto(t,x,'Subplot',[3 3 5],'Hold',1,'Maximize',1);

plotCompleto(t,xe,...
    'Hold',1,...
    'Subplot',[3 3 5],...
    'AxisLimits',[-5 5 -1 3],...
    'XLabel','t',...
    %'YLabel','$h(t^2)$',...
    'Title','Ej 6 e) - P1',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',2);

legend('h(t)','h(t^2)','location','northwest');

%% f)
xf = (tri1(t) - tri1(-t))/2;

plotCompleto(t,x,'Subplot',[3 3 6],'Hold',1,'Maximize',1);

plotCompleto(t,xf,...
    'Hold',1,...
    'Subplot',[3 3 6],...
    'AxisLimits',[-6 6 -2 2.5],...
    'XLabel','t',...
    %'YLabel','$Impar\{h(t)\}$',...
    'Title','Ej 6 f) - P1',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',2);

legend('h(t)','Impar\{h(t)\}','location','northwest');

%% g)
xg = (tri1(t) + tri1(-t))/2;

plotCompleto(t,x,'Subplot',[3 3 7],'Hold',1,'Maximize',1);

plotCompleto(t,xg,...
    'Hold',1,...
    'Subplot',[3 3 7],...
    'AxisLimits',[-6 6 -0.5 2.5],...
    'XLabel','t',...
    %'YLabel','$Par\{h(t)\}$',...
    'Title','Ej 6 g) - P1',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',2);

legend('h(t)','Par\{h(t)\}','location','northwest');
