addpath('Funciones');

clear all; close all; clc;

% Defino intervalo de las muestras y vector a utilizar
N = 10;
n = -N:N;

% Entradas para probar los sistemas

% Entrada x[n] = 5.d[n]
x1 = 5 * deltaKronecker(n);

% Entrada x[n] = 3.d[n-1]
x2 = 3 * deltaKronecker(n-1);

% Entrada x[n] = d[n] + 2.d[n-1]
x3 = deltaKronecker(n) + 2*deltaKronecker(n-1);



% Sistema S1 y[n] = x[n] + a.x[n-1]

% Constantes del sistema
R = 1;
a = 1/2;




y1_1 = S1(x1,a,R);
stemCompleto(n,y1_1,...
  'AxisLimits',[-5 5 -6 6],...
  'Hold',1,...
  'Subplot',[2 3 1],...
  'XLabel','n',...
  'YLabel','S1',...
  'Title','Entrada x[n] = 5.d[n]',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

legend('y1_1[n]','location','northwest');

y1_2 = S1(x2,a,R);
stemCompleto(n,y1_2,...
  'AxisLimits',[-5 5 -6 6],...
  'Hold',1,...
  'Subplot',[2 3 2],...
  'XLabel','n',...
  'Title','Entrada x[n] = 3.d[n-1]',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

legend('y1_2[n]','location','northwest');

y1_3 = S1(x3,a,R);
stemCompleto(n,y1_3,...
  'AxisLimits',[-5 5 -6 6],...
  'Hold',1,...
  'Subplot',[2 3 3],...
  'XLabel','n',...
  'Title','Entrada x[n] = d[n] + 2.d[n-1]',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

legend('y1_3[n]','location','northwest');


% Sistema S5 y[n] = n.x[n]

y2_1 = n.*x1;

stemCompleto(n,y2_1,...
  'AxisLimits',[-5 5 -6 6],...
  'Hold',1,...
  'Subplot',[2 3 4],...
  'XLabel','n',...
  'YLabel','S2',...
  'Title','Entrada x[n] = 5.d[n]',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

legend('y2_1[n]','location','northwest');



y2_2 = n.*x2;

stemCompleto(n,y2_2,...
  'AxisLimits',[-5 5 -6 6],...
  'Hold',1,...
  'Subplot',[2 3 5],...
  'XLabel','n',...
  'Title','Entrada x[n] = 3.d[n-1]',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

legend('y2_2[n]','location','northwest');



y2_1 = n.*x3;

stemCompleto(n,y2_1,...
  'AxisLimits',[-5 5 -6 6],...
  'Hold',1,...
  'Subplot',[2 3 6],...
  'XLabel','n',...
  'Title','Entrada x[n] = d[n] + 2.d[n-1]',...
  'FontSize', 20,...
  'LineStyle','-',...
  'Color','r',...
  'MarkerFaceColor','r',...
  'MarkerEdgeColor','r',...
  'LineWidth',3);

legend('y2_3[n]','location','northwest');

