%% Ej 7 P1  -  AnSyS - IPS
% Limpiamos la ventana de comandos, borramos todas las variables, cerramos
% todas las figuras.
clear all;close all;clc;
% Añadimos directorio con definiciones de funciones útiles
addpath('../../funciones')

%% a)
% señales en el tiempo (dist. uniforme)

N = 10e3; n = 1:N; x = rand(1,N);

plotCompleto(n,x,...
    'Maximize',1,...
    'Subplot',[2 1 1],...
    'AxisLimits',[n(1) n(end) -1 2],...
    'XLabel','$n$',...
    'YLabel','$rand(1,N)$',...
    'Title','Ej 7 a) - P1',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',1);

y = 10*(rand(1,N) - 1/2);       
subplot(2,1,2);

plotCompleto(n,y,...
    'Hold',1,...
    'Subplot',[2 1 2],...
    'AxisLimits',[n(1) n(end) -7 7],...
    'XLabel','$n$',...
    'YLabel','$10(rand(1,N)-1/2)$',...
    'Title','Ej 7 a) - P1',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',1);

% histogramas de las señales
figure('units','normalized','outerposition',[0 0 1 1]) % Creo y maximizo figura.
bins = 15;
subplot(2,1,1);histCompleto([-1 2 0 2*N/bins],'$x$','$Frecuencia$','Histograma de $x$',20,x,bins)
subplot(2,1,2);histCompleto([-6 6 0 2*N/bins],'$y$','$Frecuencia$','Histograma de $y$',20,y,bins)

%% b)

N = 10e3; n = 1:N; z = randn(1,N); 
bins = 20;

% señal en el tiempo (dist. Normal(0,1))
plotCompleto(n,z,...
    'Maximize',1,...
    'Subplot',[2 1 1],...
    'AxisLimits',[n(1) n(end) -4 4],...
    'XLabel','$n$',...
    'YLabel','$rand(1,N)$',...
    'Title','Ej 7 b) - P1',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',1);

% histograma de la distribución normal
subplot(2,1,2);
histCompleto([-6 6 0 4*N/bins],'$z$','$Frecuencia$','Histograma de $z$',20,z,bins)

%% c)

N = 10e3; M=20; n=1:N; x = rand(M,N)-0.5; y = sum(x,1); 
bins = 20;

plotCompleto(n,z,...
    'Maximize',1,...
    'Subplot',{2 2 4},...
    'AxisLimits',[n(1) n(end) -10 10],...
    'XLabel','$n$',...
    'YLabel','$y[n]$',...
    'Title','Se\~nal $y[n]$',...
    'FontSize',20,...
    'LineStyle','r.-',...
    'LineWidth',1.5);

% histograma de las M V.A con distribución uniforme
subplot(2,2,[1 2]);histCompleto([-1 1 0 2*N/bins],'$x$','$Frecuencia$','Histograma de $x$ (20 V.A. uniformes)',20,x.',bins)
% histograma de la V.A que es suma de las M V.A uniformes. Vemos que la
% distribución resultante es Normal.
subplot(2,2,3);histCompleto([-10 10 0 4*N/bins],'$y$','$Frecuencia$','Histograma de $y$ (suma de las V.A. uniformes)',20,y.',bins)